"""Auto migration

Revision ID: 67870affc3b8
Revises: 78f4c5e858fe
Create Date: 2025-06-18 22:39:48.699095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67870affc3b8'
down_revision = '78f4c5e858fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocklist')
    # ### end Alembic commands ###
